[project]
name = "python-file-server"
version = "0.1.0"
description = "Python file server project managed by uv"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastapi>=0.141.1",
    "loguru>=0.7.3",
    "python-multipart>=0.0.32",
    "uvicorn[standard]>=0.52.4",
]
